### ISSUE TITLE
Error 500 Server Error Nuclio when Deploying Model AI 

### ISSUE THREAD

**Issue by ruhyadi** [danilhendrasr/semi-automated-labeling#3]
Error 500 saat deploying model AI ke CVAT

![error-500](https://user-images.githubusercontent.com/39303602/168751611-5a66b5cc-2aee-42a1-ab60-c409204fc547.png)

Error terjadi saat deploy model yang sama (sebelumnya sudah di-deploy). Jika deploy model baru tidak mengalami erro tersebut.

**Comment by ruhyadi** [comment]
Untuk mengatasi error ini, masuk ke server Nuclio terlebih dahulu melalui [localhost:8070](http://localhost:8070). Setelahnya, hapus model yang akan di deploy ulang. Setelah model terhapus, deploy ulang model menggunakan `deploy_cpu.sh` atau `deploy_gpu.sh`.
Butuh ditambahkan **documentation** @dwifajrian

**Comment by danilhendrasr** [comment]
Dokumentasinya pindah ke wiki atau tetep di gitbook yak?

**Comment by ruhyadi** [comment]
Ke wiki dulu ajah kali ya, nulisnya lebih enak dan lebih cepat daripada di gitbook. Mungkin yg private2 masih di gitbook.

**Comment by danilhendrasr** [comment]
Cc @dwifajrian
